# encoding: utf8

# Import local files:
import colors as COLORS
import margins as MARGINS
import roi as ROI


# External:
external = ROI.ROI('External', 'External', COLORS.external)
x_external = ROI.ROI('xExternal', 'Organ', COLORS.external)
body = ROI.ROI('Body', 'Organ', COLORS.body)


# Support:
#couch = ROI.ROI('Couch', 'Support', COLORS.couch)
couch = ROI.ROI('Couch', 'Undefined', COLORS.wall)

# Target volumes:
gtv = ROI.ROI('GTV', 'Gtv', COLORS.gtv)
ctv = ROI.ROIExpanded('CTV', 'Ctv', COLORS.ctv, gtv, margins = MARGINS.uniform_5mm_expansion)
ptv = ROI.ROIExpanded('PTV', 'Ptv', COLORS.ptv, ctv, margins = MARGINS.uniform_5mm_expansion)
ctv_ext = ROI.ROIAlgebra('CTV', 'Ctv', COLORS.ctv, sourcesA = [gtv], sourcesB = [external], operator = 'Intersection', marginsA = MARGINS.uniform_5mm_expansion, marginsB = MARGINS.uniform_5mm_contraction)
ptv_ext = ROI.ROIAlgebra('PTV', 'Ptv', COLORS.ptv, sourcesA = [ctv], sourcesB = [external], operator = 'Intersection', marginsA = MARGINS.uniform_5mm_expansion, marginsB = MARGINS.uniform_5mm_contraction)
ptv_ext_7 = ROI.ROIAlgebra('PTV', 'Ptv', COLORS.ptv, sourcesA = [ctv], sourcesB = [external], operator = 'Intersection', marginsA = MARGINS.uniform_7mm_expansion, marginsB = MARGINS.uniform_5mm_contraction)
ctv_underived = ROI.ROI('CTV', 'Ctv', COLORS.ctv)
igtv = ROI.ROI('IGTV', 'Gtv', COLORS.gtv)
igtv1 = ROI.ROI('IGTV1', 'Gtv', COLORS.gtv)
igtv2 = ROI.ROI('IGTV2', 'Gtv', COLORS.gtv)
igtv3 = ROI.ROI('IGTV3', 'Gtv', COLORS.gtv)
ictv = ROI.ROIExpanded('ICTV', 'Ctv', COLORS.ctv, igtv, margins = MARGINS.uniform_5mm_expansion)
#ictv = ROI.ROIAlgebra('ICTV', 'Ctv', COLORS.ctv, sourcesA = [igtv], sourcesB = [lungs], operator = 'Intersection', marginsA = MARGINS.uniform_5mm_expansion, marginsB = MARGINS.zero)
ictv1 = ROI.ROIExpanded('ICTV1', 'Ctv', COLORS.ctv, igtv1, margins = MARGINS.uniform_5mm_expansion)
ictv2 = ROI.ROIExpanded('ICTV2', 'Ctv', COLORS.ctv, igtv2, margins = MARGINS.uniform_5mm_expansion)
ictv3 = ROI.ROIExpanded('ICTV3', 'Ctv', COLORS.ctv, igtv3, margins = MARGINS.uniform_5mm_expansion)

iptv = ROI.ROIExpanded('PTV', 'Ptv', COLORS.ptv, ictv, margins = MARGINS.uniform_5mm_expansion)
iptv1 = ROI.ROIExpanded('PTV1', 'Ptv', COLORS.ptv, ictv1, margins = MARGINS.uniform_5mm_expansion)
iptv2 = ROI.ROIExpanded('PTV2', 'Ptv', COLORS.ptv, ictv2, margins = MARGINS.uniform_5mm_expansion)
iptv3 = ROI.ROIExpanded('PTV3', 'Ptv', COLORS.ptv, ictv3, margins = MARGINS.uniform_5mm_expansion)
gtv_p = ROI.ROI('GTVp','Gtv', COLORS.gtv)
gtv_n = ROI.ROI('GTVn','Gtv', COLORS.gtv)
gtv_p_pt = ROI.ROI('GTVp_PT', 'Gtv', COLORS.gtv_pt)
gtv_n_pt = ROI.ROI('GTVn_PT', 'Gtv', COLORS.gtv_pt)
gtv_n1_pt = ROI.ROI('GTVn1_PT', 'Gtv', COLORS.gtv_pt)
gtv_n2_pt = ROI.ROI('GTVn2_PT', 'Gtv', COLORS.gtv_pt)
gtv_n3_pt = ROI.ROI('GTVn3_PT', 'Gtv', COLORS.gtv_pt)
gtv_n4_pt = ROI.ROI('GTVn4_PT', 'Gtv', COLORS.gtv_pt)
gtv_n5_pt = ROI.ROI('GTVn5_PT', 'Gtv', COLORS.gtv_pt)
gtv_n6_pt = ROI.ROI('GTVn6_PT', 'Gtv', COLORS.gtv_pt)
gtv_pt = ROI.ROI('GTV_PT', 'Gtv', COLORS.gtv_pt)
gtv_n1 = ROI.ROI('GTVn1','Gtv', COLORS.gtv_high)
gtv_n2 = ROI.ROI('GTVn2','Gtv', COLORS.gtv_high)
gtv_n3 = ROI.ROI('GTVn3','Gtv', COLORS.gtv_high)
gtv_n4 = ROI.ROI('GTVn4','Gtv', COLORS.gtv_high)
gtv_n5 = ROI.ROI('GTVn5','Gtv', COLORS.gtv_high)
gtv_n6 = ROI.ROI('GTVn6','Gtv', COLORS.gtv_high)
gtv_p_54 = ROI.ROI('GTVn_54','Gtv', COLORS.gtv)
gtv_p_57 = ROI.ROI('GTVn_57.5','Gtv', COLORS.gtv)
gtv_n_50 = ROI.ROI('GTVn_50','Gtv', COLORS.gtv)
gtv_n1_50 = ROI.ROI('GTVn1_50','Gtv', COLORS.gtv)
gtv_n2_50 = ROI.ROI('GTVn2_50','Gtv', COLORS.gtv)
gtv_n3_50 = ROI.ROI('GTVn3_50','Gtv', COLORS.gtv)
gtv_n4_50 = ROI.ROI('GTVn4_50','Gtv', COLORS.gtv)
gtv_n_54 = ROI.ROI('GTVn_54','Gtv', COLORS.gtv)
gtv_n1_54 = ROI.ROI('GTVn1_54','Gtv', COLORS.gtv)
gtv_n2_54 = ROI.ROI('GTVn2_54','Gtv', COLORS.gtv)
gtv_n3_54 = ROI.ROI('GTVn3_54','Gtv', COLORS.gtv)
gtv_n4_54 = ROI.ROI('GTVn4_54','Gtv', COLORS.gtv)


gtv_n_55 = ROI.ROI('GTVn_55','Gtv', COLORS.gtv)
gtv_n1_55 = ROI.ROI('GTVn1_55','Gtv', COLORS.gtv)
gtv_n2_55 = ROI.ROI('GTVn2_55','Gtv', COLORS.gtv)
gtv_n3_55 = ROI.ROI('GTVn3_55','Gtv', COLORS.gtv)
gtv_n4_55 = ROI.ROI('GTVn4_55','Gtv', COLORS.gtv)
gtv_p_57 = ROI.ROI('GTVp_57.5','Gtv', COLORS.gtv_high)
gtv_n_57 = ROI.ROI('GTVn_57.5','Gtv', COLORS.gtv_high)
gtv_n1_57 = ROI.ROI('GTVn1_57.5','Gtv', COLORS.gtv_high)
gtv_n2_57 = ROI.ROI('GTVn2_57.5','Gtv', COLORS.gtv_high)
gtv_n3_57 = ROI.ROI('GTVn3_57.5','Gtv', COLORS.gtv_high)
gtv_n4_57 = ROI.ROI('GTVn4_57.5','Gtv', COLORS.gtv_high)


gtv_p_41_4 = ROI.ROI('GTVp_41.4','Gtv', COLORS.gtv)
gtv_n_41_4 = ROI.ROI('GTVn_41.4','Gtv', COLORS.gtv)
gtv_p_50 = ROI.ROI('GTVp_50','Gtv', COLORS.gtv)
gtv_p_60 = ROI.ROI('GTVp_60','Gtv', COLORS.gtv)
gtv_n_60 = ROI.ROI('GTVn_60','Gtv', COLORS.gtv)
gtv_p_66 = ROI.ROI('GTVp_66','Gtv', COLORS.gtv)
gtv_n_66 = ROI.ROI('GTVn_66','Gtv', COLORS.gtv)
ctv_e = ROI.ROI('CTVe','Ctv', COLORS.ctv_med)
gtv_groin_l = ROI.ROI('GTV_Groin_L','Gtv', COLORS.gtv)
gtv_groin_r = ROI.ROI('GTV_Groin_R','Gtv', COLORS.gtv)
ctv_groin_l = ROI.ROI('CTV_Groin_L','Ctv', COLORS.ctv_med)
ctv_groin_r = ROI.ROI('CTV_Groin_R','Ctv', COLORS.ctv_med)
ctv_p = ROI.ROI('CTVp', 'Ctv', COLORS.ctv)
ctv_n = ROI.ROI('CTVn','Ctv', COLORS.ctv_n)
igtv_p = ROI.ROI('IGTVp','Gtv', COLORS.gtv)
igtv_n = ROI.ROI('IGTVn','Gtv', COLORS.gtv)
igtv_n1 = ROI.ROI('IGTVn1','Gtv', COLORS.gtv)
igtv_n2 = ROI.ROI('IGTVn2','Gtv', COLORS.gtv)
igtv_n3 = ROI.ROI('IGTVn3','Gtv', COLORS.gtv)
igtv_n4 = ROI.ROI('IGTVn4','Gtv', COLORS.gtv)
igtv_n5 = ROI.ROI('IGTVn5','Gtv', COLORS.gtv)
igtv_n6 = ROI.ROI('IGTVn6','Gtv', COLORS.gtv)
ictv_p = ROI.ROI('ICTVp', 'Ctv', COLORS.ctv_high)
ictv_n = ROI.ROI('ICTVn', 'Ctv', COLORS.ctv_high)
ictv_n1 = ROI.ROI('ICTVn1', 'Ctv', COLORS.ctv_high)
ictv_n2 = ROI.ROI('ICTVn2', 'Ctv', COLORS.ctv_high)
ictv_n3 = ROI.ROI('ICTVn3', 'Ctv', COLORS.ctv_high)
ictv_n4 = ROI.ROI('ICTVn4', 'Ctv', COLORS.ctv_high)
ictv_n5 = ROI.ROI('ICTVn5', 'Ctv', COLORS.ctv_high)
ictv_n6 = ROI.ROI('ICTVn6', 'Ctv', COLORS.ctv_high)
gtv1 = ROI.ROI('GTV1', 'Gtv', COLORS.gtv)
gtv2 = ROI.ROI('GTV2', 'Gtv', COLORS.gtv)
gtv3 = ROI.ROI('GTV3', 'Gtv', COLORS.gtv)
gtv4 = ROI.ROI('GTV4', 'Gtv', COLORS.gtv)
ctv1 = ROI.ROI('CTV1', 'Ctv', COLORS.ctv)
ctv2 = ROI.ROI('CTV2', 'Ctv', COLORS.ctv)
ctv3 = ROI.ROI('CTV3', 'Ctv', COLORS.ctv)
ctv4 = ROI.ROI('CTV4', 'Ctv', COLORS.ctv)
gtv_sb = ROI.ROI('GTVsb', 'Gtv', COLORS.gtv)
ctv_sb = ROI.ROI('CTVsb', 'Ctv', COLORS.ctv)
vb = ROI.ROI('VB','Ctv', COLORS.ctv_med)
ctv_e_l_54 = ROI.ROI('CTVe_L_54', 'Ctv', COLORS.ctv_low_2)
ctv_e_r_54 = ROI.ROI('CTVe_R_54', 'Ctv', COLORS.ctv_low_2)
ctv_e_l_50 = ROI.ROI('CTVe_L_50', 'Ctv', COLORS.ctv_low_2)
ctv_e_r_50 = ROI.ROI('CTVe_R_50', 'Ctv', COLORS.ctv_low_2)
ctv_boost = ROI.ROI('CTVboost', 'Ctv', COLORS.ctv_low_2)

# OARs: Empty (will be delineated manually):
# Head:
#eye_l = ROI.ROI('Eye_L', 'Organ', COLORS.eye)
#eye_r = ROI.ROI('Eye_R', 'Organ', COLORS.eye)
lens_l = ROI.ROI('Lens_L', 'Organ', COLORS.lens_l)
lens_r = ROI.ROI('Lens_R', 'Organ', COLORS.lens)
optic_nrv_l = ROI.ROI('OpticNerve_L', 'Organ', COLORS.optic_nrv_l)
optic_nrv_r = ROI.ROI('OpticNerve_R', 'Organ', COLORS.optic_nrv)
optic_chiasm = ROI.ROI('OpticChiasm','Organ', COLORS.chiasma)
lacrimal_l =ROI.ROI('LacrimalGland_L', 'Organ', COLORS.lacrimal_l)
lacrimal_r =ROI.ROI('LacrimalGland_R', 'Organ', COLORS.lacrimal)
cochlea_l = ROI.ROI('Cochlea_L','Organ', COLORS.cochlea_l)
cochlea_r = ROI.ROI('Cochlea_R','Organ', COLORS.cochlea)
hippocampus_l = ROI.ROI('Hippocampus_L','Organ', COLORS.hippocampus_l)
hippocampus_r = ROI.ROI('Hippocampus_R','Organ', COLORS.hippocampus)
brainstem = ROI.ROI('Brainstem', 'Organ', COLORS.brainstem)
nasal_cavity = ROI.ROI('NasalCavity', 'Organ', COLORS.nasal_cavity)
pituitary = ROI.ROI('Pituitary', 'Organ', COLORS.pituitary)
submand_l = ROI.ROI('SubmandGland_L', 'Organ', COLORS.submand)
submand_r = ROI.ROI('SubmandGland_R', 'Organ', COLORS.submand)
#mandible = ROI.ROI('Mandible', 'Organ', COLORS.mandible)
cornea_l = ROI.ROI('Cornea_L', 'Organ', COLORS.cornea_l) 
cornea_r = ROI.ROI('Cornea_R', 'Organ', COLORS.cornea)
retina_l = ROI.ROI('Retina_L', 'Organ', COLORS.retina_l) 
retina_r = ROI.ROI('Retina_R', 'Organ', COLORS.retina)
brainstem_core = ROI.ROIExpanded('BrainstemCore', 'Organ', COLORS.brainstem_core, brainstem, margins = MARGINS.uniform_2mm_contraction)
brainstem_surface = ROI.ROIAlgebra('BrainstemSurface', 'Organ', COLORS.brainstem_surface, sourcesA = [brainstem], sourcesB = [brainstem_core], operator = 'Subtraction')
a_carotid_l =  ROI.ROI('A_Carotid_L', 'Organ', COLORS.carotid)
a_carotid_r =  ROI.ROI('A_Carotid_R', 'Organ', COLORS.carotid)
# Thorax:
esophagus = ROI.ROI('Esophagus', 'Organ', COLORS.esophagus)
esophagus_ = ROI.ROI('Esophagus~', 'Organ', COLORS.esophagus)
spinal_cord = ROI.ROI('SpinalCord', 'Organ', COLORS.spinal_cord)
heart = ROI.ROI('Heart', 'Organ', COLORS.heart)
bronchus = ROI.ROI('Bronchus','Organ', COLORS.main_bronchus)
a_aorta = ROI.ROI('A_Aorta','Organ', COLORS.heart)
brachial_plexus = ROI.ROI('BrachialPlexus','Organ',COLORS.brachial)
brachial_plexus_r = ROI.ROI('BrachialPlexus_R','Organ',COLORS.brachial)
brachial_plexus_l = ROI.ROI('BrachialPlexus_L','Organ',COLORS.brachial)
# Breast:
muscle = ROI.ROI('ScaleneMusc', 'Undefined', COLORS.muscle)
contralat_breast = ROI.ROI('Contralat breast', 'Organ', COLORS.contralat)
contralat_draft = ROI.ROI('Contralat breast draft', 'Organ', COLORS.contralat_draft)
lad = ROI.ROI('A_LAD','Organ', COLORS.lad)
a_lad = ROI.ROI('A_LAD','Organ', COLORS.lad)
humeral_l = ROI.ROI('HumeralHead_L', 'Organ', COLORS.heart_prv)
humeral_r = ROI.ROI('HumeralHead_R', 'Organ', COLORS.heart_prv)
thyroid = ROI.ROI('Thyroid', 'Organ', COLORS.thyroid)
# Lung, stereotactic:
chestwall = ROI.ROI('Chestwall', 'Organ', COLORS.chestwall)
greatves = ROI.ROI('GreatVessel','Organ', COLORS.heart)
trachea = ROI.ROI('Trachea','Organ', COLORS.trachea)
trachea_ = ROI.ROI('Trachea~','Organ', COLORS.trachea)
bronchus_ = ROI.ROI('Bronchus~','Organ', COLORS.main_bronchus)
stomach = ROI.ROI('Stomach','Organ', COLORS.stomach)
liver = ROI.ROI('Liver','Organ', COLORS.liver)
rib_x_l = ROI.ROI('Ribx_L','Organ', COLORS.rib)
rib_x_r = ROI.ROI('Ribx_R','Organ', COLORS.rib)
rib_y_l = ROI.ROI('Riby_L','Organ', COLORS.rib)
rib_y_r = ROI.ROI('Riby_R','Organ', COLORS.rib)
ribs = ROI.ROI('Ribs','Organ', COLORS.ribs)
main_bronchus_l = ROI.ROI('BronchusMain_L','Organ', COLORS.main_bronchus)
main_bronchus_r = ROI.ROI('BronchusMain_R','Organ', COLORS.main_bronchus)
connective_tissue =ROI.ROI('ConnectiveTissue','Organ', COLORS.bladder)
x_chestwall = ROI.ROI('xChestwall','Undefined',COLORS.chestwall)

# Spine SBRT:
cauda_equina = ROI.ROI('CaudaEquina','Organ', COLORS.cauda)
small_bowel = ROI.ROI('BowelSmall','Organ', COLORS.small_bowel)
colon = ROI.ROI('Colon','Organ', COLORS.colon)
brachial = ROI.ROI('BrachialPlexus','Organ', COLORS.brachial)

# Pelvis
bowel_bag = ROI.ROI('BowelBag', 'Organ', COLORS.bowel_bag)
bowel_space = ROI.ROI('BowelBag', 'Organ', COLORS.bowel_space)
rectum = ROI.ROI('Rectum', 'Organ', COLORS.rectum)
# Gyn
sigmoid = ROI.ROI('Sigmoid','Organ', COLORS.penile_bulb)
ovary_r = ROI.ROI('Ovary_R','Organ', COLORS.ovary)
ovary_l = ROI.ROI('Ovary_L','Organ', COLORS.ovary)
# Prostate
pelvic_nodes = ROI.ROI('LN_Iliac', 'Ctv', COLORS.pelvic_nodes)
prostate = ROI.ROI('Prostate', 'Ctv', COLORS.prostate)
prostate_bed = ROI.ROI('SurgicalBed', 'Ctv', COLORS.prostate_bed)
vesicles = ROI.ROI('SeminalVes', 'Ctv', COLORS.vesicles)
anal_canal = ROI.ROI('AnalCanal','Organ', COLORS.anal_canal)
penile_bulb = ROI.ROI('PenileBulb','Organ', COLORS.penile_bulb)

genitals = ROI.ROI('Genitals','Organ', COLORS.penile_bulb)

# Undefined/ other ROIs
# Breast organs:
surgical_bed = ROI.ROI('SurgicalBed','Undefined', COLORS.breast_draft)
imn = ROI.ROI('CTVn_IMN', 'Ctv', COLORS.imn)
breast_l_draft = ROI.ROI('Breast_L_Draft', 'Ctv', COLORS.breast_draft)
breast_r_draft = ROI.ROI('Breast_R_Draft', 'Ctv', COLORS.breast_draft)
breast_l_contralat_draft = ROI.ROI('Breast_L_Draft', 'Undefined', COLORS.contralat_draft)
breast_r_contralat_draft = ROI.ROI('Breast_R_Draft', 'Undefined', COLORS.contralat_draft)
breast_draft = ROI.ROI('Breast draft', 'Undefined', COLORS.breast_draft)
breast_l = ROI.ROIAlgebra('Breast_L', 'Organ', COLORS.contralat, sourcesA = [breast_l_contralat_draft], sourcesB = [body], operator = 'Intersection', marginsA = MARGINS.zero, marginsB = MARGINS.uniform_5mm_contraction)
breast_r = ROI.ROIAlgebra('Breast_R', 'Organ', COLORS.contralat, sourcesA = [breast_r_contralat_draft], sourcesB = [body], operator = 'Intersection', marginsA = MARGINS.zero, marginsB = MARGINS.uniform_5mm_contraction)

level4_l = ROI.ROI('CTVn_L4', 'Ctv', COLORS.level4)
level3_l = ROI.ROI('CTVn_L3', 'Ctv', COLORS.level3)
level2_l = ROI.ROI('CTVn_L2', 'Ctv', COLORS.level2)
level1_l = ROI.ROI('CTVn_L1', 'Ctv', COLORS.level1)
level_l = ROI.ROI('CTVn_Interpect', 'Ctv', COLORS.level)
level4_r = ROI.ROI('CTVn_L4', 'Ctv', COLORS.level4)
level3_r = ROI.ROI('CTVn_L3', 'Ctv', COLORS.level3)
level2_r = ROI.ROI('CTVn_L2', 'Ctv', COLORS.level2)
level1_r = ROI.ROI('CTVn_L1', 'Ctv', COLORS.level1)
level_r = ROI.ROI('CTVn_Interpect', 'Ctv', COLORS.level)
artery1_l = ROI.ROI('A_Subclavian_L', 'Undefined', COLORS.artery1)
artery2_l = ROI.ROI('A_Carotid_L', 'Undefined', COLORS.artery2)
vein1_l = ROI.ROI('V_Brachioceph+V_Subclavian_L', 'Undefined', COLORS.vein1)
vein2_l = ROI.ROI('V_Jugular_L','Undefined', COLORS.vein2)
muscle = ROI.ROI('ScaleneMusc', 'Undefined', COLORS.muscle)
artery1_r = ROI.ROI('A_Brachioceph+A_Subclavian_R', 'Undefined', COLORS.artery1)
artery2_r = ROI.ROI('A_Carotid_R', 'Undefined', COLORS.artery2)
vein1_r = ROI.ROI('V_Brachioceph+V_Subclavian_R', 'Undefined', COLORS.vein1)
vein2_r = ROI.ROI('V_Jugular_R','Undefined', COLORS.vein2)
muscle = ROI.ROI('ScaleneMusc', 'Undefined', COLORS.muscle)
prosthesis = ROI.ROI('Prosthesis','Undefined', COLORS.prosthesis)
prosthesis_l = ROI.ROI('Prosthesis_L','Undefined', COLORS.prosthesis)
prosthesis_r = ROI.ROI('Prosthesis_R','Undefined', COLORS.prosthesis)
sternum = ROI.ROI('Sternum','Organ', COLORS.heart_prv)
parotid_l = ROI.ROI('Parotid_L', 'Organ', COLORS.parotid)
parotid_r = ROI.ROI('Parotid_R', 'Organ', COLORS.parotid_r)
# Markers:
clips = ROI.ROI('Markers', 'Marker', COLORS.clips)
markers = ROI.ROI('Markers', 'Marker', COLORS.clips)
seed1 = ROI.ROI('Marker1', 'Marker', COLORS.seed)
seed2 = ROI.ROI('Marker2', 'Marker', COLORS.seed)
seed3 = ROI.ROI('Marker3', 'Marker', COLORS.seed)
seed4 = ROI.ROI('Marker4', 'Marker', COLORS.seed)
marker1 = ROI.ROI('Marker1', 'Marker', COLORS.seed)
marker2 = ROI.ROI('Marker2', 'Marker', COLORS.seed)
marker3 = ROI.ROI('Marker3', 'Marker', COLORS.seed)
marker4 = ROI.ROI('Marker4', 'Marker', COLORS.seed)
temp_markers = ROI.ROI('tempMarkers', 'Marker', COLORS.seed)


# OARs: MBS (delineated by model based segmentation):
brain = ROI.ROI('Brain', 'Organ', COLORS.brain, case ='HeadNeck', model = 'Brain')
#brainstem = ROI.ROI('Brainstem', 'Organ', COLORS.brainstem, case ='HeadNeck',  model = 'Brainstem')
spinal_canal = ROI.ROI('SpinalCanal', 'Organ', COLORS.spinal_canal, case ='Thorax',  model = 'SpinalCord (Thorax)')
spinal_canal_head = ROI.ROI('SpinalCanal', 'Organ', COLORS.spinal_canal, case ='HeadNeck',  model =  'SpinalCord')
#parotid_l = ROI.ROI('Parotid_L', 'Organ', COLORS.parotid, case ='HeadNeck',  model = 'ParotidGland (Left)')
#parotid_r = ROI.ROI('Parotid_R', 'Organ', COLORS.parotid, case ='HeadNeck',  model = 'ParotidGland (Right)')
mandible = ROI.ROI('Mandible', 'Organ', COLORS.mandible, case ='HeadNeck',  model = 'Mandible')
lung_l =  ROI.ROI('Lung_L', 'Organ', COLORS.lung, case ='Thorax',  model =  'Lung (Left)')
lung_r =  ROI.ROI('Lung_R', 'Organ', COLORS.lung_r, case ='Thorax',  model = 'Lung (Right)')
kidney_l = ROI.ROI('Kidney_L', 'Organ', COLORS.kidney, case ='Abdomen',  model = 'Kidney (Left)')
kidney_r = ROI.ROI('Kidney_R', 'Organ', COLORS.kidney, case ='Abdomen',  model = 'Kidney (Right)')
bladder = ROI.ROI('Bladder', 'Organ', COLORS.bladder, case ='PelvicMale',  model = 'Bladder')
femoral_l = ROI.ROI('FemoralHead_L', 'Organ', COLORS.femoral, case = 'PelvicMale', model = 'FemoralHead (Left)')
femoral_r = ROI.ROI('FemoralHead_R', 'Organ', COLORS.femoral_r, case = 'PelvicMale', model = 'FemoralHead (Right)')

eye_l = ROI.ROI('Eye_L', 'Organ', COLORS.eye_l, case ='HeadNeck', model ='Eye (Left)')
eye_r = ROI.ROI('Eye_R', 'Organ', COLORS.eye, case ='HeadNeck', model ='Eye (Right)')

# OARs: Unions:
parotids = ROI.ROIAlgebra('Parotids', 'Organ', COLORS.parotid, sourcesA=[parotid_l], sourcesB=[parotid_r])
submands = ROI.ROIAlgebra('SubmandGlands', 'Organ', COLORS.submand, sourcesA=[submand_l], sourcesB=[submand_r])
lungs =  ROI.ROIAlgebra('Lungs', 'Organ', COLORS.lungs, sourcesA=[lung_l], sourcesB=[lung_r])
kidneys =  ROI.ROIAlgebra('Kidneys', 'Organ', COLORS.kidneys, sourcesA=[kidney_l], sourcesB=[kidney_r])
ribs_l = ROI.ROIAlgebra('Ribs_L','Organ', COLORS.ribs, sourcesA=[rib_x_l], sourcesB=[rib_y_l])
ribs_r = ROI.ROIAlgebra('Ribs_R','Organ', COLORS.ribs, sourcesA=[rib_x_r], sourcesB=[rib_y_r])
lungs_igtv = ROI.ROIAlgebra('Lungs-IGTV', 'Organ', COLORS.lungs, sourcesA=[lungs], sourcesB=[igtv], operator = 'Subtraction')


# OARs: Target subtracted
# Other:
other_ptv = ROI.ROI('Other_PTV', 'Organ', COLORS.other_ptv)


# PRVs:
brainstem_prv = ROI.ROIExpanded('Brainstem_PRV', 'Avoidance', COLORS.prv, source=brainstem, margins=MARGINS.uniform_3mm_expansion)
eye_l_prv = ROI.ROIExpanded('Eye_PRV_L', 'Avoidance', COLORS.prv, source=eye_l, margins=MARGINS.uniform_3mm_expansion)
eye_r_prv = ROI.ROIExpanded('Eye_PRV_R', 'Avoidance', COLORS.prv, source=eye_r, margins=MARGINS.uniform_3mm_expansion)
lens_l_prv = ROI.ROIExpanded('Lens_PRV_L', 'Avoidance', COLORS.prv, source=lens_l, margins=MARGINS.uniform_3mm_expansion)
lens_r_prv = ROI.ROIExpanded('Lens_PRV_R', 'Avoidance', COLORS.prv, source=lens_r, margins=MARGINS.uniform_3mm_expansion)
optic_nrv_l_prv = ROI.ROIExpanded('OpticNerve_PRV_L', 'Avoidance', COLORS.prv, source=optic_nrv_l, margins=MARGINS.uniform_3mm_expansion)
optic_nrv_r_prv = ROI.ROIExpanded('OpticNerve_PRV_R', 'Avoidance', COLORS.prv, source=optic_nrv_r, margins=MARGINS.uniform_3mm_expansion)
optic_chiasm_prv = ROI.ROIExpanded('OpticChiasm_PRV','Avoidance', COLORS.prv, source=optic_chiasm, margins=MARGINS.uniform_3mm_expansion)
lacrimal_l_prv =ROI.ROIExpanded('LacrimalGland_PRV_L', 'Avoidance', COLORS.prv, source=lacrimal_l, margins=MARGINS.uniform_3mm_expansion)
lacrimal_r_prv =ROI.ROIExpanded('LacrimalGland_PRV_R', 'Avoidance', COLORS.prv, source=lacrimal_r, margins=MARGINS.uniform_3mm_expansion)
spinal_cord_prv = ROI.ROIExpanded('SpinalCord_PRV', 'Avoidance', COLORS.prv, source=spinal_cord, margins=MARGINS.uniform_3mm_expansion)
z_spinal_canal = ROI.ROIExpanded('zSpinalCanal', 'Undefined', COLORS.prv,source=spinal_canal, margins=MARGINS.uniform_5mm_expansion)
bronchus_prv = ROI.ROIExpanded('Bronchus_PRV', 'Avoidance', COLORS.prv, source=bronchus, margins=MARGINS.uniform_5mm_expansion)
trachea_prv = ROI.ROIExpanded('Trachea_PRV', 'Avoidance', COLORS.prv, source=trachea, margins=MARGINS.uniform_5mm_expansion)
esophagus_prv = ROI.ROIExpanded('Esophagus_PRV', 'Avoidance', COLORS.prv, source=esophagus, margins=MARGINS.uniform_5mm_expansion)
spinal_cord_narlal_prv = ROI.ROIExpanded('SpinalCord_PRV', 'Avoidance', COLORS.prv, source=spinal_cord, margins=MARGINS.uniform_5mm_expansion)
spinal_cord_prv_2 = ROI.ROIExpanded('SpinalCord_PRV', 'Avoidance', COLORS.prv, source=spinal_cord, margins=MARGINS.uniform_2mm_expansion)
brainstem_prv_2 = ROI.ROIExpanded('Brainstem_PRV', 'Avoidance', COLORS.prv, source=brainstem, margins=MARGINS.uniform_2mm_expansion)
heart_prv =  ROI.ROIExpanded('Heart_PRV', 'Avoidance', COLORS.heart_prv, source=heart, margins=MARGINS.uniform_5mm_expansion)
# Walls:
skin_srt = ROI.ROIWall('Skin','Organ', COLORS.skin, body, 0, 0.3)
skin = ROI.ROIWall('Skin','Organ', COLORS.skin, external, 0, 0.3)
skin_brain_5 = ROI.ROIWall('Skin','Organ', COLORS.skin, body, 0, 0.5)
skin_brain = ROI.ROIWall('Skin','Organ', COLORS.skin, external, 0, 0.5)
wall_ptv = ROI.ROIWall('zPTV_Wall', 'Undefined', COLORS.wall, iptv, 1, 0)
wall_ptv1 = ROI.ROIWall('zPTV1_Wall', 'Undefined', COLORS.wall, iptv1, 1, 0)
wall_ptv2 = ROI.ROIWall('zPTV2_Wall', 'Undefined', COLORS.wall, iptv2, 1, 0)
wall_ptv3 = ROI.ROIWall('zPTV3_Wall', 'Undefined', COLORS.wall, iptv3, 1, 0)
x_ptv_ring_05 =  ROI.ROI('xPTV_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv1_ring_05 =  ROI.ROI('xPTV1_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv2_ring_05 =  ROI.ROI('xPTV2_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv3_ring_05 =  ROI.ROI('xPTV3_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv4_ring_05 =  ROI.ROI('xPTV4_Ring0-0.5cm', 'Undefined', COLORS.wall)
x_ptv_ring_2 =  ROI.ROI('xPTV_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv1_ring_2 =  ROI.ROI('xPTV1_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv2_ring_2 =  ROI.ROI('xPTV2_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv3_ring_2 =  ROI.ROI('xPTV3_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ptv4_ring_2 =  ROI.ROI('xPTV4_Ring0.5-2cm', 'Undefined', COLORS.wall)
x_ctv_n_ring = ROI.ROI('xCTVn_L3-L4_Ring', 'Undefined', COLORS.wall)
z_match = ROI.ROI('zMatch', 'Registration', COLORS.match)
x_tetthetsvolum = ROI.ROI('xTetthetsvolum', 'Undefined', COLORS.wall)
# ROIs for optimization:
z_crp = ROI.ROI('zCRP', 'Undefined', COLORS.wall)
z_water =  ROI.ROI('zWater', 'Undefined', COLORS.other_ptv)
z_heart =  ROI.ROI('zHeart', 'Undefined', COLORS.heart)
z_esophagus =  ROI.ROI('zEsophagus', 'Undefined', COLORS.esophagus)
z_bladder = ROI.ROI('zBladder','Undefined', COLORS.bladder)
x_bowelbag = ROI.ROI('xBowelBag','Undefined', COLORS.bowel_space)
z_spc_bowel = ROI.ROI('zBowelBag','Undefined', COLORS.bowel_space)
z_rectum = ROI.ROI('zRectum', 'Undefined', COLORS.rectum)

dorso_rectum = ROI.ROI('zRectum_P', 'Undefined', COLORS.dorso_rectum)
z_rectum_p = ROI.ROI('zRectum_P', 'Undefined', COLORS.dorso_rectum)
z_ptv_77_wall = ROI.ROI('zPTV_77_Wall', 'Undefined', COLORS.wall)
z_ptv_70_77_wall = ROI.ROI('zPTV_70+77_Wall', 'Undefined', COLORS.wall)
z_ptv_60_wall = ROI.ROI('zPTV_60_Wall', 'Undefined', COLORS.wall)
z_ptv_50_wall = ROI.ROI('zPTV_50_Wall', 'Undefined', COLORS.wall)
z_ptv_57_60_wall = ROI.ROI('zPTV_57+60_Wall', 'Undefined', COLORS.wall)
z_ptv_70_wall = ROI.ROI('zPTV_70_Wall', 'Undefined', COLORS.wall)
z_ptv_56_temp = ROI.ROI('zPTV_56_Temp', 'Undefined', COLORS.wall)
z_ptv_56_wall = ROI.ROI('zPTV_56_Wall', 'Undefined', COLORS.wall)
z_ptv_wall = ROI.ROI('zPTV_Wall', 'Undefined', COLORS.wall)
z_ptv1_wall = ROI.ROI('zPTV1_Wall', 'Undefined', COLORS.wall)
z_ptv2_wall = ROI.ROI('zPTV2_Wall', 'Undefined', COLORS.wall)
z_ptv3_wall = ROI.ROI('zPTV3_Wall', 'Undefined', COLORS.wall)
z_ptv4_wall = ROI.ROI('zPTV4_Wall', 'Undefined', COLORS.wall)
ctv_oars = ROI.ROI('zCTV-OARs', 'Ctv', COLORS.ctv)
ptv_oars = ROI.ROI('zPTV-OARs', 'Ptv', COLORS.ptv)
ptv_and_oars = ROI.ROI('zPTV_AND_OARs', 'Ptv', COLORS.other_ptv)
z_eye_l = ROI.ROIWall('zEye_L','Undefined', COLORS.wall, eye_l, 0, 0.2)
z_eye_r = ROI.ROIWall('zEye_R','Undefined', COLORS.wall, eye_r, 0, 0.2)
x_sparevolum = ROI.ROI('xSparevolum','Undefined', COLORS.x_sparevolum)
x_skulder_h = ROI.ROI('xSkulder_H','Undefined',COLORS.x_sparevolum)
x_skulder_v = ROI.ROI('xSkulder_V','Undefined',COLORS.x_sparevolum)
x_bekkenbein = ROI.ROI('xBekkenbein','Undefined',COLORS.x_bekkenbein)
x_ctv_54 = ROI.ROI('xCTV!_54','Undefined',COLORS.x_ctv_54)
x_ptv_54 = ROI.ROI('xPTV!_54','Undefined',COLORS.x_ptv_54)
x_ctv_60 = ROI.ROI('xCTV!_60','Undefined',COLORS.x_ctv_60)
x_ptv_60 = ROI.ROI('xPTV!_60','Undefined',COLORS.x_ptv_60)
x_ctv_50 = ROI.ROI('xCTV!_50','Undefined',COLORS.x_ctv_54)
x_ptv_50 = ROI.ROI('xPTV!_50','Undefined',COLORS.x_ptv_54)
x_gtv_p = ROI.ROI('xGTVp','Undefined',COLORS.x_gtv_p)
x_ptv_45 = ROI.ROI('xPTV!_45','Undefined',COLORS.x_ptv_45)
x_ptv_41 = ROI.ROI('xPTV!_41.6','Undefined',COLORS.x_ptv_54)
x_ctv_41 = ROI.ROI('xCTV!_41.6','Undefined',COLORS.x_ctv_54)
x_ctv_e = ROI.ROI('xCTVe','Undefined',COLORS.x_ctv_54)
x_ptv_lunge = ROI.ROI('xPTV_lunge','Undefined',COLORS.x_ptv_54)
x_ptv_vev = ROI.ROI('xPTV_vev','Undefined',COLORS.x_ptv_54)
z_mask = ROI.ROI('zMask','Undefined',COLORS.z_mask)
x_ctv_46 = ROI.ROI('xCTV!_46','Undefined',COLORS.x_ctv_54)
x_ptv_46 = ROI.ROI('xPTV!_46','Undefined',COLORS.x_ptv_54)
# Substitute ROI objects (only used for naming):
# Targets:
ptv_n1 = ROI.ROI('PTVn1', 'Ptv', COLORS.ptv)
ptv_n2 = ROI.ROI('PTVn2', 'Ptv', COLORS.ptv)
ptv_n3 = ROI.ROI('PTVn3', 'Ptv', COLORS.ptv)
ptv_n4 = ROI.ROI('PTVn4', 'Ptv', COLORS.ptv)
ptv_n5 = ROI.ROI('PTVn5', 'Ptv', COLORS.ptv)
ptv_n6 = ROI.ROI('PTVn6', 'Ptv', COLORS.ptv)

ptv_n_imn = ROI.ROI('PTVn_IMN', 'Ptv', COLORS.ptv_high)
x_ptv_n = ROI.ROI('xPTVn', 'Undefined', COLORS.ptv)
x_ptv_p = ROI.ROI('xPTVp', 'Undefined', COLORS.x_ptv_54)
ptv_boost = ROI.ROI('PTVboost', 'Ptv', COLORS.ptv)
ptv_77 = ROI.ROI('PTV_77', 'Ptv', COLORS.ptv_high)
ptv_70 = ROI.ROI('PTV_70', 'Ptv', COLORS.ptv_med)
ptv_70_sib = ROI.ROI('PTV!_70', 'Ptv', COLORS.ptv_med)
ctv_77 = ROI.ROI('CTV_77', 'Ctv', COLORS.ctv_high)
ctv_70 = ROI.ROI('CTV_70', 'Ctv', COLORS.ctv_med)
ctv_70_sib = ROI.ROI('CTV!_70', 'Ctv', COLORS.ctv_med)
ptv_56 = ROI.ROI('PTV!_56', 'Ptv', COLORS.ptv_low)
ctv_56 = ROI.ROI('CTV!_56', 'Ctv', COLORS.ctv_low)

ptv_p1_77 = ROI.ROI('PTVp1_77', 'Ptv', COLORS.ptv_high)
ptv_70 = ROI.ROI('PTV_70', 'Ptv', COLORS.ptv_med)
ptv_p2_70 = ROI.ROI('PTVp2_70', 'Ptv', COLORS.ptv_med)
ctv_p1_77 = ROI.ROI('CTVp1_77', 'Ctv', COLORS.ctv_high)
ctv_p2_70 = ROI.ROI('CTVp2_70', 'Ctv', COLORS.ctv_med_2)
ctv_e_56 = ROI.ROI('CTVe_56','Ctv', COLORS.ctv_med)
ptv_e_56 = ROI.ROI('PTVe_56', 'Ptv', COLORS.ptv_low)
ptv_n_70 = ROI.ROI('PTVn_70', 'Ptv', COLORS.ptv_med)
ctv_n_70 = ROI.ROI('CTVn_70', 'Ctv', COLORS.ctv_med_3)


ptv_sb_70 = ROI.ROI('PTVsb_70', 'Ptv', COLORS.ptv_med)
ctv_sb_70 = ROI.ROI('CTVsb_70', 'Ctv', COLORS.ctv_high)

x_ptv_56 = ROI.ROI('xPTV!_56', 'Undefined', COLORS.ptv_low)
x_ctv_56 = ROI.ROI('xCTV!_56', 'Undefined', COLORS.ctv_low)
x_ptv_70 = ROI.ROI('xPTV!_70', 'Undefined', COLORS.ptv_med)
ptv_p1_60 = ROI.ROI('PTVp1_60', 'Ptv', COLORS.ptv_high)
ctv_p1_60 = ROI.ROI('CTVp1_60', 'Ctv', COLORS.ctv_high)
ptv_p2_60 = ROI.ROI('PTVp2_60', 'Ptv', COLORS.ptv_med)
ctv_p2_60 = ROI.ROI('CTVp2_60', 'Ctv', COLORS.ctv_med_2)
ptv_60 = ROI.ROI('PTV_60', 'Ptv', COLORS.ptv_low)
ctv_60 = ROI.ROI('CTV_60', 'Ctv', COLORS.ctv_low)
ptv_70_77 = ROI.ROI('PTV_70+77', 'Ptv', COLORS.ptv_low)
ctv_70_77 = ROI.ROI('CTV_70+77', 'Ctv', COLORS.ctv_low)
ptv_57_60 = ROI.ROI('PTV_57+60', 'Ptv', COLORS.ptv_low)
ctv_57_60 = ROI.ROI('CTV_57+60', 'Ctv', COLORS.ctv_low)
ptv_56_70_77 = ROI.ROI('PTV_56+70+77', 'Ptv', COLORS.ptv_low)
ptv_56_70 = ROI.ROI('PTV_56+70', 'Ptv', COLORS.ptv_low)

ptv_57 = ROI.ROI('PTV!_57', 'Ptv', COLORS.ptv_med)
ctv_57 = ROI.ROI('CTV!_57', 'Ctv', COLORS.ctv_med)
ptv_pc =  ROI.ROI('PTVpc', 'Ptv', COLORS.x_ptv_54)
ptv_p = ROI.ROI('PTVp', 'Ptv', COLORS.x_ptv_54)
ptv_n =  ROI.ROI('PTVn', 'Ptv', COLORS.ptv)

ptv_nc =  ROI.ROI('PTVnc', 'Ptv', COLORS.ptv)
ptv1 =  ROI.ROI('PTV1', 'Ptv', COLORS.ptv)
ptv2 =  ROI.ROI('PTV2', 'Ptv', COLORS.ptv)
ptv3 =  ROI.ROI('PTV3', 'Ptv', COLORS.ptv)
ptv4 =  ROI.ROI('PTV4', 'Ptv', COLORS.ptv)
ptv_c = ROI.ROI('PTVc', 'Ptv', COLORS.ptv)
x_ptv = ROI.ROI('xPTV', 'Ptv', COLORS.ptv)
x_ptv_caud = ROI.ROI('xPTVcaud', 'Undefined', COLORS.ptv)
x_ptv_cran = ROI.ROI('xPTVcran', 'Undefined', COLORS.ptv)
ptv_sb = ROI.ROI('PTVsb', 'Ptv', COLORS.ptv)
ptv_sbc = ROI.ROI('PTVsbc', 'Ptv', COLORS.ptv)
ctv_47_50 =  ROI.ROI('CTV_47+50', 'Ctv', COLORS.ctv_low)
ptv_47_50 =  ROI.ROI('PTV_47+50', 'Ptv', COLORS.ptv_low)
ptv_50 = ROI.ROI('PTV_50', 'Ptv', COLORS.ptv_high)
ptv_50c = ROI.ROI('PTV_50c', 'Ptv', COLORS.ptv_high)
ctv_50 = ROI.ROI('CTV_50', 'Ctv', COLORS.ctv_high)
ctv_47 =  ROI.ROI('CTV!_47', 'Ctv', COLORS.ctv_low)
ctv_47_tot =  ROI.ROI('CTV_47', 'Ctv', COLORS.ctv_low)
ptv_47 =  ROI.ROI('PTV!_47', 'Ptv', COLORS.ptv_med)
ptv_47_tot =  ROI.ROI('PTV_47', 'Ptv', COLORS.ptv_med)
ptv_47c =  ROI.ROI('PTV!_47c', 'Ptv', COLORS.ptv_med)
ptv_semves = ROI.ROI('PTV_SeminalVes', 'Ptv', COLORS.ptv_med)

# Gyn
ctv_30 = ROI.ROI('CTV_30','Ctv', COLORS.ctv_low_2)
ctv_50 = ROI.ROI('CTV_50','Ctv', COLORS.ctv_low_2)
ctv_ln_l = ROI.ROI('CTV_LN_L','Ctv', COLORS.ctv_low_2)
ctv_ln_r = ROI.ROI('CTV_LN_R','Ctv', COLORS.ctv_low_2)
ctv_45 = ROI.ROI('CTV_45','Ctv', COLORS.ctv_low_2)
ctv_e_30 = ROI.ROI('CTVe_30','Ctv', COLORS.ctv_low_2)
ctv_e_45 = ROI.ROI('CTVe_45','Ctv', COLORS.ctv_low_2)
ctv_e_50 = ROI.ROI('CTVe_50','Ctv', COLORS.ctv_low_2)
ctv_p_30 = ROI.ROI('CTVp_30', 'Ctv', COLORS.ctv_med)
ctv_p_45 = ROI.ROI('CTVp_45', 'Ctv', COLORS.ctv_med)
ctv_p_50 = ROI.ROI('CTVp_50', 'Ctv', COLORS.ctv_med)
ptv_p_45 = ROI.ROI('PTVp_45', 'Ptv', COLORS.ptv_med_2) #endre farge
ptv_e_45 = ROI.ROI('PTVe_45','Ptv',COLORS.ptv_med)
ptv_30 = ROI.ROI('PTV_30','Ptv',COLORS.ptv_med)
ptv_45 = ROI.ROI('PTV_45','Ptv',COLORS.ptv_med)
ptv_50 = ROI.ROI('PTV_50','Ptv',COLORS.ptv_med)
ctv_n_50 = ROI.ROI('CTVn_50', 'Ctv', COLORS.ctv_med)
ctv_n1_50 = ROI.ROI('CTVn1_50', 'Ctv', COLORS.ctv_med)
ctv_n2_50 = ROI.ROI('CTVn2_50', 'Ctv', COLORS.ctv_med)
ctv_n3_50 = ROI.ROI('CTVn3_50', 'Ctv', COLORS.ctv_med)
ctv_n4_50 = ROI.ROI('CTVn4_50', 'Ctv', COLORS.ctv_med)
ctv_n_55 = ROI.ROI('CTVn_55', 'Ctv', COLORS.ctv_med)
ctv_n1_55 = ROI.ROI('CTVn1_55', 'Ctv', COLORS.ctv_med)
ctv_n2_55 = ROI.ROI('CTVn2_55', 'Ctv', COLORS.ctv_med)
ctv_n3_55 = ROI.ROI('CTVn3_55', 'Ctv', COLORS.ctv_med)
ctv_n4_55 = ROI.ROI('CTVn4_55', 'Ctv', COLORS.ctv_med)
ctv_n_57 = ROI.ROI('CTVn_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n1_57 = ROI.ROI('CTVn1_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n2_57 = ROI.ROI('CTVn2_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n3_57 = ROI.ROI('CTVn3_57.5', 'Ctv', COLORS.ctv_high_2)
ctv_n4_57 = ROI.ROI('CTVn4_57.5', 'Ctv', COLORS.ctv_high_2)
ptv_n_55 =ROI.ROI('PTVn_55', 'Ptv', COLORS.ptv_med_2)
ptv_n1_55 =ROI.ROI('PTVn1_55', 'Ptv', COLORS.ptv_med_2)
ptv_n2_55 =ROI.ROI('PTVn2_55', 'Ptv', COLORS.ptv_med_2)
ptv_n3_55 =ROI.ROI('PTVn3_55', 'Ptv', COLORS.ptv_med_2)
ptv_n4_55 =ROI.ROI('PTVn4_55', 'Ptv', COLORS.ptv_med_2)
ptv_n_57 =ROI.ROI('PTVn_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n1_57 =ROI.ROI('PTVn1_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n2_57 =ROI.ROI('PTVn2_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n3_57 =ROI.ROI('PTVn3_57.5', 'Ptv', COLORS.ptv_high_2)
ptv_n4_57 =ROI.ROI('PTVn4_57.5', 'Ptv', COLORS.ptv_high_2)

# Øsofagus
ctv_p_41_4 = ROI.ROI('CTVp_41.4', 'Ctv', COLORS.ctv_high_2)
ptv_p_41_4 = ROI.ROI('PTVp_41.4', 'Ptv', COLORS.ptv_high_2)
ctv_e_41_4 = ROI.ROI('CTVe_41.4','Ctv', COLORS.ctv_low_2)
ptv_e_41_4 = ROI.ROI('PTVe_41.4','Ptv',COLORS.ptv_med)
ctv_n_41_4 =ROI.ROI('CTVn_41.4', 'Ctv', COLORS.ctv_med_2)
ptv_n_41_4 =ROI.ROI('PTVn_41.4', 'Ptv', COLORS.ptv_med_2)
ctv_e_46 = ROI.ROI('CTVe_46','Ctv', COLORS.ctv_low_2)
ptv_e_46 = ROI.ROI('PTVe_46','Ptv',COLORS.ptv_med)
ptv_41_4 = ROI.ROI('PTV_41.4','Ptv',COLORS.ptv_med)

ctv_n_66 =ROI.ROI('CTVn_66', 'Ctv', COLORS.ctv_med_2)
ptv_n_66 =ROI.ROI('PTVn_66', 'Ptv', COLORS.ptv_med_2)
ctv_p_66 = ROI.ROI('CTVp_66', 'Ctv', COLORS.ctv_high_2)
ptv_p_66 = ROI.ROI('PTVp_66', 'Ptv', COLORS.ptv_high_2)
ptv_66 = ROI.ROI('PTV_66','Ptv',COLORS.ptv_high)
# Rectum
ctv_sb_50 = ROI.ROI('CTVsb_50', 'Ctv', COLORS.ctv_high_2)
ptv_sb_50 = ROI.ROI('PTVsb_50', 'Ptv', COLORS.ptv_high_2)
ctv_e_ln_l_46 = ROI.ROI('CTVe_LN_L_46.5','Ctv', COLORS.ctv_low_2)
ctv_e_ln_r_46 = ROI.ROI('CTVe_LN_R_46.5','Ctv', COLORS.ctv_low_2)
ptv_e_ln_r_46 = ROI.ROI('PTVe_LN_R_46.5','Ptv', COLORS.ptv_low)
ptv_e_ln_l_46 = ROI.ROI('PTVe_LN_L_46.5','Ptv', COLORS.ptv_low)
ctv_n_50 =ROI.ROI('CTVn_50', 'Ctv', COLORS.ctv_med_2)
ptv_n_50 =ROI.ROI('PTVn_50', 'Ptv', COLORS.ptv_med_2)
ctv_e_46_5 = ROI.ROI('CTVe_46.5','Ctv', COLORS.ctv_low_2)
ptv_e_46_5 = ROI.ROI('PTVe_46.5','Ptv',COLORS.ptv_med)

# Anus
ctv_e_41 = ROI.ROI('CTVe_41.6','Ctv', COLORS.ctv_low_2)
ptv_e_41 = ROI.ROI('PTVe_41.6','Ptv',COLORS.ptv_med)
ctv_p_50 = ROI.ROI('CTVp_50', 'Ctv', COLORS.ctv_high_2)
ptv_p_50 = ROI.ROI('PTVp_50', 'Ptv', COLORS.ptv_high_2)
ctv_p_54 = ROI.ROI('CTVp_54', 'Ctv', COLORS.ctv_high_2)
ptv_p_54 = ROI.ROI('PTVp_54', 'Ptv', COLORS.ptv_high_2)
ctv_p_57 = ROI.ROI('CTVp_57.5', 'Ctv', COLORS.ctv_high_2)
ptv_p_57 = ROI.ROI('PTVp_57.5', 'Ptv', COLORS.ptv_high_2)
ctv_n_54 =ROI.ROI('CTVn_54', 'Ctv', COLORS.ctv_med_2)
ptv_n_54 =ROI.ROI('PTVn_54', 'Ptv', COLORS.ptv_med_2)
ctv_n1_54 =ROI.ROI('CTVn1_54', 'Ctv', COLORS.ctv_med_2)
ptv_n1_54 =ROI.ROI('PTVn1_54', 'Ptv', COLORS.ptv_med_2)
ctv_n2_54 =ROI.ROI('CTVn2_54', 'Ctv', COLORS.ctv_med_2)
ptv_n2_54 =ROI.ROI('PTVn2_54', 'Ptv', COLORS.ptv_med_2)
ctv_n3_54 =ROI.ROI('CTVn3_54', 'Ctv', COLORS.ctv_med_2)
ptv_n3_54 =ROI.ROI('PTVn3_54', 'Ptv', COLORS.ptv_med_2)
ctv_n4_54 =ROI.ROI('CTVn4_54', 'Ctv', COLORS.ctv_med_2)
ptv_n4_54 =ROI.ROI('PTVn4_54', 'Ptv', COLORS.ptv_med_2)
ctv_e_ln_l_41 = ROI.ROI('CTVe_LN_L_41.6','Ctv', COLORS.ctv_low)
ctv_e_ln_r_41 = ROI.ROI('CTVe_LN_R_41.6','Ctv', COLORS.ctv_low)
ptv_e_ln_r_41 = ROI.ROI('PTVe_LN_R_41.6','Ptv', COLORS.ptv_low)
ptv_e_ln_l_41 = ROI.ROI('PTVe_LN_L_41.6','Ptv', COLORS.ptv_low)

ctv_e = ROI.ROI('CTVe','Ctv', COLORS.ctv_low_2)
ptv_e = ROI.ROI('PTVe','Ptv',COLORS.ptv_med)

ctv_e_54 = ROI.ROI('CTVe_54','Ctv', COLORS.ctv_low_2)
ctv_e_50 = ROI.ROI('CTVe_50','Ctv', COLORS.ctv_low_2)
ptv_e_54 = ROI.ROI('PTVe_54','Ptv',COLORS.ptv_med)
ptv_e_50 = ROI.ROI('PTVe_50','Ptv',COLORS.ptv_med)
ptv_e_l_54 = ROI.ROI('PTVe_L_54','Ptv',COLORS.ptv_med)
ptv_e_r_54 = ROI.ROI('PTVe_R_54','Ptv',COLORS.ptv_med)
ctv_sb_60 = ROI.ROI('CTVsb_60', 'Ctv', COLORS.ctv_med)
ctv_sb_66 = ROI.ROI('CTVsb_66', 'Ctv', COLORS.ctv_high_2)
ptv_sb_60 =ROI.ROI('PTVsb_60', 'Ptv', COLORS.ptv_med_2)
ptv_sb_66 = ROI.ROI('PTVsb_66', 'Ptv', COLORS.ptv_high_2)
ctv_p_60 = ROI.ROI('CTVp_60', 'Ctv', COLORS.ctv_med)
ctv_p_66 = ROI.ROI('CTVp_66', 'Ctv', COLORS.ctv_high_2)
ctv_p_68 = ROI.ROI('CTVp_68', 'Ctv', COLORS.ctv_high_2)
ctv_p_70 = ROI.ROI('CTVp_70', 'Ctv', COLORS.ctv_high_2)
ptv_p_60 =ROI.ROI('PTVp_60', 'Ptv', COLORS.ptv_med_2)
ptv_p_66 = ROI.ROI('PTVp_66', 'Ptv', COLORS.ptv_high_2)
ptv_p_68 = ROI.ROI('PTVp_68', 'Ptv', COLORS.ptv_high_2)
ptv_p_70 = ROI.ROI('PTVp_70', 'Ptv', COLORS.ptv_high_2)
ctv_n_60 = ROI.ROI('CTVn_60', 'Ctv', COLORS.ctv_med)
ctv_n_68 = ROI.ROI('CTVn_68', 'Ctv', COLORS.ctv_high_2)
ctv_n_70 = ROI.ROI('CTVn_70', 'Ctv', COLORS.ctv_high_2)
ctv_n1_60 = ROI.ROI('CTVn1_60', 'Ctv', COLORS.ctv_med)
ctv_n1_68 = ROI.ROI('CTVn1_68', 'Ctv', COLORS.ctv_high_2)
ctv_n1_70 = ROI.ROI('CTVn1_70', 'Ctv', COLORS.ctv_high_2)
ctv_n2_60 = ROI.ROI('CTVn2_60', 'Ctv', COLORS.ctv_med)
ctv_n2_68 = ROI.ROI('CTVn2_68', 'Ctv', COLORS.ctv_high_2)
ctv_n2_70 = ROI.ROI('CTVn2_70', 'Ctv', COLORS.ctv_high_2)
ctv_n3_60 = ROI.ROI('CTVn3_60', 'Ctv', COLORS.ctv_med)
ctv_n3_68 = ROI.ROI('CTVn3_68', 'Ctv', COLORS.ctv_high_2)
ctv_n3_70 = ROI.ROI('CTVn3_70', 'Ctv', COLORS.ctv_high_2)
ptv_n_60 =ROI.ROI('PTVn_60', 'Ptv', COLORS.ptv_med_2)
ptv_n_68 = ROI.ROI('PTVn_68', 'Ptv', COLORS.ptv_high_2)
ptv_n_70 = ROI.ROI('PTVn_70', 'Ptv', COLORS.ptv_high_2)
ptv_n1_70 = ROI.ROI('PTVn1_70', 'Ptv', COLORS.ptv_high_2)
ptv_n2_70 = ROI.ROI('PTVn2_70', 'Ptv', COLORS.ptv_high_2)
ptv_n3_70 = ROI.ROI('PTVn3_70', 'Ptv', COLORS.ptv_high_2)
# Miscellaneous:
brain_gtv = ROI.ROI('Brain-GTV','Organ', COLORS.brain)
brain_ptv = ROI.ROI('Brain-PTV','Organ', COLORS.other_ptv)
lungs_gtv = ROI.ROI('Lungs-GTV', 'Organ', COLORS.lungs)
lungs_ctv = ROI.ROI('Lungs-CTV', 'Organ', COLORS.lungs)
ptv_gtv = ROI.ROI('PTV-GTV', 'Ptv', COLORS.ptv_med)
ptv_spinal = ROI.ROI('PTV-SpinalCord_PRV', 'Ptv', COLORS.ptv_med) # FIXME: Fra nasjanoal anbefaling skal formen PTVc brukes her...
mask_ptv = ROI.ROI('Mask_PTV','Undefined', COLORS.mask_ptv)
mask_ptv1 = ROI.ROI('Mask_PTV1','Undefined', COLORS.mask_ptv)
mask_ptv2 = ROI.ROI('Mask_PTV2','Undefined', COLORS.mask_ptv)
mask_ptv3 = ROI.ROI('Mask_PTV3','Undefined', COLORS.mask_ptv)
box = ROI.ROI('zBox','Undefined', COLORS.mask_ptv)
box1 = ROI.ROI('zBox1','Undefined', COLORS.mask_ptv)
box_l = ROI.ROI('zBox_L','Undefined', COLORS.mask_ptv)
box_r = ROI.ROI('zBox_R','Undefined', COLORS.mask_ptv)
box3 = ROI.ROI('zBox3','Undefined', COLORS.mask_ptv)
box4 = ROI.ROI('zBox4','Undefined', COLORS.mask_ptv)
x_l2_l4 = ROI.ROI('xL2-L4','Undefined', COLORS.mask_ptv)


# NB!! Nye volumer i Trondheim
x_body_fripust = ROI.ROI('xBody_fripust', 'Organ', COLORS.x_body_fripust)
z_brain = ROI.ROI('zBrain', 'Undefined', COLORS.brain)
brain_eks = ROI.ROI('Brain^ekskludert', 'Undefined', COLORS.brain)
brain_gtv_eks = ROI.ROI('Brain-GTV^ekskludert','Organ', COLORS.brain)
brain_ptv_eks = ROI.ROI('Brain-PTV^ekskludert','Organ', COLORS.brain)
brainstem_prv_03 = ROI.ROIExpanded('Brainstem_PRV03', 'Avoidance', COLORS.prv, source=brainstem, margins=MARGINS.uniform_3mm_expansion)
brainstem_surface_prv_03 = ROI.ROIExpanded('BrainstemSurface_PRV03', 'Avoidance', COLORS.prv, source=brainstem_surface, margins=MARGINS.uniform_3mm_expansion)
spinal_cord_prv_03 = ROI.ROIExpanded('SpinalCord_PRV03', 'Avoidance', COLORS.prv, source=spinal_cord, margins=MARGINS.uniform_3mm_expansion)
optic_nrv_l_prv_03 = ROI.ROIExpanded('OpticNerve_L_PRV03', 'Avoidance', COLORS.prv, source=optic_nrv_l, margins=MARGINS.uniform_3mm_expansion)
optic_nrv_r_prv_03 = ROI.ROIExpanded('OpticNerve_R_PRV03', 'Avoidance', COLORS.prv, source=optic_nrv_r, margins=MARGINS.uniform_3mm_expansion)
optic_chiasm_prv_03 = ROI.ROIExpanded('OpticChiasm_PRV03','Avoidance', COLORS.prv, source=optic_chiasm, margins=MARGINS.uniform_3mm_expansion)
retina_l_prv_03 = ROI.ROIExpanded('Retina_L_PRV03','Avoidance', COLORS.prv, source=retina_l, margins=MARGINS.uniform_3mm_expansion)
retina_r_prv_03 = ROI.ROIExpanded('Retina_R_PRV03','Avoidance', COLORS.prv, source=retina_r, margins=MARGINS.uniform_3mm_expansion)
cornea_l_prv_03 = ROI.ROIExpanded('Cornea_L_PRV03','Avoidance', COLORS.prv, source=cornea_l, margins=MARGINS.uniform_3mm_expansion)
cornea_r_prv_03 = ROI.ROIExpanded('Cornea_R_PRV03','Avoidance', COLORS.prv, source=cornea_r, margins=MARGINS.uniform_3mm_expansion)


